services:
  - type: web
    name: crla-parser
    env: python

    buildCommand: |
      apt-get update
      apt-get install -y poppler-utils
      pip install -r requirements.txt

    startCommand: gunicorn app:app
